### PR TITLE
adding provider to convert

### PR DESCRIPTION
**Pull request by steve-fraser**
**What this PR does / why we need it**:

Added missing provider to convert method

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Callisto13** [comment]
Thanks @steve-fraser could you fix the tests and push again?

**Comment by steve-fraser** [comment]
@Callisto13 do you need to approve it to run the test?

**Comment by Callisto13** [comment]
@steve-fraser are you running the build or tests locally before you push?

**Comment by steve-fraser** [comment]
@Callisto13 I wasn't before, but I did now and everything seems to be passing after a few commits :)

**Review by richardcase — APPROVED** [review]

**Pull request merged**
