### PR TITLE
Update ci and dependabot config

### LINKED ISSUE #866: Use built in dependabot bundler
**Describe the solution you'd like:**
Update the dependabot bundling to use the builtin functionality

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:

- update dependabot config
- apply best practices and update actions

cc @richardcase 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #866 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by richardcase** [comment]
Thanks @cpanato , this is  great

**Comment by cpanato** [comment]
@richardcase rebased PTAL

**Review by richardcase — APPROVED** [review]
LGTM....very much appreciated.

**Comment by cpanato** [comment]
> LGTM....very much appreciated.

i will check other things in this repo and move to the others :)

**Comment by richardcase** [comment]
> i will check other things in this repo and move to the others :)

Thanks @cpanato . I'm going to re-open a bunch of issues as well because the stale bot workflow closed them.

**Pull request merged**
